name: Check
on: pull_request

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint:fix
